module.exports = {
  RECEIVE_ALL_INDEX: "RECEIVE_ALL_INDEX",
  RECEIVE_ALL_KLASS_INDEX: "RECEIVE_ALL_KLASS_INDEX",
  RECEIVE_MY_KLASSES: "RECEIVE_MY_KLASSES",
  RECEIVE_STUDY_SETS: "RECEIVE_STUDY_SETS",
  FILL_STUDY_SET_POOL: "FILL_STUDY_SET_POOL",
  RECEIVE_BY_LANGUAGE: "RECEIVE_BY_LANGUAGE",
  RECEIVE_ALL_LANGUAGES: "RECEIVE_ALL_LANGUAGES"

  // RECEIVE_LANGUAGE_INDEX: "RECEIVE_LANGUAGE_INDEX",
  // RECEIVE_SEARCH_RESULT: "RECEIVE_SEARCH_RESULT"

};
