module.exports = {
  RECEIVE_ALL_KLASS_INDEX: "RECEIVE_ALL_KLASS_INDEX",
  RECEIVE_CREATED_KLASS_INDEX: "RECEIVE_CREATED_KLASS_INDEX",
  RECEIVE_ENROLLED_KLASS_INDEX: "RECEIVE_ENROLLED_KLASS_INDEX",
  RECEIVE_STUDY_SET_INDEX: "RECEIVE_STUDY_SET_INDEX",
  RECEIVE_SEARCH_RESULT: "RECEIVE_SEARCH_RESULT"

};
